
transform_tolerance: 3
obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.05, -0.05], [-0.05, 0.05], [0.021, 0.05], [0.021, -0.05]]
robot_radius: 0.06

inflation_radius: 0.05
cost_scaling_factor: 15

map_type: costmap
observation_sources: scan
scan: {sensor_frame: robot2_tf/base_scan, data_type: LaserScan, topic: robot2/scan, marking: true, clearing: true}
