local_costmap:
    # footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]

    # footprint_padding: 0.01 
    transform_tolerance: 3
    update_frequency: 10
    publish_frequency: 10
    width: 2
    height: 2
    resolution: 0.05
    origin_x: 0
    origin_y: 0
    global_frame: robot2_tf/odom
    robot_base_frame: robot2_tf/base_footprint
    static_map: false
    rolling_window: true

    plugins:
        - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
        # - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

    # inflation_layer:   
    #     enabled:              true
    #     cost_scaling_factor:  20  #
    #     inflation_radius: 0.01  #5
    #     inflate_unknown: false

    obstacle_layer:
        enabled: true
        combination_method: 1
        max_obstacle_height: 2
        footprint_clearing_end: true 
        obstacle_range: 3.0 #5.0
        raytrace_range: 3.5 #5.5
        observation_sources: laser_scan_sensor
        laser_scan_sensor: {data_type: LaserScan, topic: robot2/scan, marking: true, clearing: true}