
global_costmap:
  footprint: [[0.7, 0.25], [0.7, -0.25], [-0.1, -0.25], [-0.1, 0.25]]
  footprint_padding: 0.15 #0.01
  robot_radius: 0.8
  transform_tolerance: 3

  update_frequency: 10
  publish_frequency: 8
  width: 20
  height: 20
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0

  global_frame: map
  robot_base_frame: base_link

  static_map: true
  rolling_window: false
  map_type: costmap 

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  obstacle_layer:
      enabled: true
      obstacle_range: 8 #5.0
      raytrace_range: 8.5 #5.5
      max_obstacle_height: 2
      footprint_clearing_end: true 
      combination_method: 1

      observation_sources: laser_scan_sensor
      laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  10  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     2.4  # 2.5 max. distance from an obstacle at which costs are incurred for planning paths.
    inflate_unknown: false
    

  static_layer:
    enabled:              true
    map_topic:            "/map"
