local_costmap:
    footprint: [[0.7, 0.25], [0.7, -0.25], [-0.1, -0.25], [-0.1, 0.25]]
    footprint_padding: 0.15 #0.01
    transform_tolerance: 3
    update_frequency: 10
    publish_frequency: 10
    width: 10
    height: 10
    resolution: 0.05
    origin_x: 0
    origin_y: 0
    global_frame: map
    robot_base_frame: base_link
    static_map: false
    rolling_window: true

    plugins:
        - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

    inflation_layer:   
        enabled:              true
        cost_scaling_factor:  10  #
        inflation_radius: 2.4  #5
        inflate_unknown: false

    obstacle_layer:
        enabled: true
        combination_method: 1
        max_obstacle_height: 2
        footprint_clearing_end: true 
        obstacle_range: 8 #5.0
        raytrace_range: 8.5 #5.5
        observation_sources: laser_scan_sensor
        laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}