
global_costmap:
  # footprint: [[-0.05, -0.05], [-0.05, 0.05], [0.021, 0.05], [0.021, -0.05]]
  # footprint_padding: 0.01 
  robot_radius: 0.105
  transform_tolerance: 3

  update_frequency: 10
  publish_frequency: 8
  # width: 10
  # height: 10
  resolution: 0.01
  # origin_x: 0.0
  # origin_y: 0.0

  global_frame: map
  # global_frame: robot1_tf/odom

  robot_base_frame: robot1_tf/base_footprint

  static_map: true
  rolling_window: false
  map_type: costmap 

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  # obstacle_layer:
  #     enabled: true
  #     obstacle_range: 5.0 
  #     raytrace_range: 5.5 
  #     max_obstacle_height: 2
  #     footprint_clearing_end: true 
  #     combination_method: 1

  #     observation_sources: laser_scan_sensor
  #     laser_scan_sensor: {data_type: LaserScan, topic: robot1/scan, marking: true, clearing: true}

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  5
    inflation_radius:     0.12  
    inflate_unknown: false
    

  static_layer:
    enabled:              true
    map_topic:            "/map"
